//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public long Id { get; set; }
        public long BaseQuestionId { get; set; }
        public long ResponseFormId { get; set; }
        public Nullable<decimal> Score { get; set; }
        public string Observation { get; set; }
    
        public virtual basequestion basequestion { get; set; }
        public virtual responseform responseform { get; set; }
    }
}
