//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class baseform
    {
        public baseform()
        {
            this.baseblocks = new HashSet<baseblock>();
            this.responseforms = new HashSet<responseform>();
        }
    
        public long Id { get; set; }
        public long PeriodId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<baseblock> baseblocks { get; set; }
        public virtual period period { get; set; }
        public virtual ICollection<responseform> responseforms { get; set; }
    }
}
