//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class baseblock
    {
        public baseblock()
        {
            this.basequestions = new HashSet<basequestion>();
        }
    
        public long Id { get; set; }
        public long BaseFormId { get; set; }
        public string Name { get; set; }
        public decimal Weight { get; set; }
        public int Index { get; set; }
    
        public virtual baseform baseform { get; set; }
        public virtual ICollection<basequestion> basequestions { get; set; }
    }
}
