//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class basequestion
    {
        public basequestion()
        {
            this.answers = new HashSet<answer>();
        }
    
        public long Id { get; set; }
        public long BaseBlockId { get; set; }
        public string Question { get; set; }
        public decimal Value { get; set; }
        public int Index { get; set; }
        public string Tip { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual baseblock baseblock { get; set; }
    }
}
