//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FdtConnection : DbContext
    {
        public FdtConnection()
            : base("name=FdtConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<answer> answers { get; set; }
        public DbSet<baseblock> baseblocks { get; set; }
        public DbSet<baseform> baseforms { get; set; }
        public DbSet<basequestion> basequestions { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<entity> entities { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<period> periods { get; set; }
        public DbSet<responseform> responseforms { get; set; }
        public DbSet<state> states { get; set; }
        public DbSet<submit> submits { get; set; }
        public DbSet<user> users { get; set; }
    }
}
