//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public long Id { get; set; }
        public long CityId { get; set; }
        public long ResponsableId { get; set; }
    
        public virtual city city { get; set; }
        public virtual user user { get; set; }
    }
}
