//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.groups = new HashSet<group>();
            this.responseforms = new HashSet<responseform>();
        }
    
        public long Id { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int UserType { get; set; }
    
        public virtual entity entity { get; set; }
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<responseform> responseforms { get; set; }
    }
}
