//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string APPROVED {
            get {
                return ResourceManager.GetString("APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Município já foi solicitado.
        /// </summary>
        internal static string city_already_requested {
            get {
                return ResourceManager.GetString("city_already_requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação ou atualização de usuários entidades não é permitida por usuários do tipo {0}  (Apenas por Adm. e Adm. Master).
        /// </summary>
        internal static string entity_users_update_or_create_not_allowed_by {
            get {
                return ResourceManager.GetString("entity_users_update_or_create_not_allowed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado para publicação.
        /// </summary>
        internal static string ENUM_SUBMITTYPE_APPROVED {
            get {
                return ResourceManager.GetString("ENUM_SUBMITTYPE_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovado e aguardando revisão.
        /// </summary>
        internal static string ENUM_SUBMITTYPE_REPROVED {
            get {
                return ResourceManager.GetString("ENUM_SUBMITTYPE_REPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submetido.
        /// </summary>
        internal static string ENUM_SUBMITTYPE_SUBMITTED {
            get {
                return ResourceManager.GetString("ENUM_SUBMITTYPE_SUBMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string ENUM_USERTYPE_ADMIN {
            get {
                return ResourceManager.GetString("ENUM_USERTYPE_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário comum.
        /// </summary>
        internal static string ENUM_USERTYPE_COMMON {
            get {
                return ResourceManager.GetString("ENUM_USERTYPE_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        internal static string ENUM_USERTYPE_ENTITY {
            get {
                return ResourceManager.GetString("ENUM_USERTYPE_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade credenciada.
        /// </summary>
        internal static string ENUM_USERTYPE_ENTITY_NETWORK {
            get {
                return ResourceManager.GetString("ENUM_USERTYPE_ENTITY_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador Master.
        /// </summary>
        internal static string ENUM_USERTYPE_MASTER {
            get {
                return ResourceManager.GetString("ENUM_USERTYPE_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string ENUM_USERTYPE_SITE {
            get {
                return ResourceManager.GetString("ENUM_USERTYPE_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário inválido.
        /// </summary>
        internal static string invalid_user {
            get {
                return ResourceManager.GetString("invalid_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apenas administradores master podem criar outros usuários administradores.
        /// </summary>
        internal static string just_master_admin_can_be_create_admin_users {
            get {
                return ResourceManager.GetString("just_master_admin_can_be_create_admin_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de usuários adm. master não permitido.
        /// </summary>
        internal static string master_admin_creation_not_allowed {
            get {
                return ResourceManager.GetString("master_admin_creation_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do bloco base deve ter no máximo 100 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_BASEBLOCK_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_BASEBLOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do formulário base deve ter no máximo 100 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_BASEFORM_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_BASEFORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da cidade deve ter no máximo 200 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_CITY_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_CITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da entidade deve ter no máximo 150 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_ENTITY_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_ENTITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do período deve ter no máximo 50 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_PERIOD_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_PERIOD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do estado deve ter no máximo 50 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_STATE_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_STATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email do usuário deve ter no máximo 50 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_USER_EMAIL {
            get {
                return ResourceManager.GetString("MAX_LENGTH_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário deve ter no máximo 20 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_USER_LOGIN {
            get {
                return ResourceManager.GetString("MAX_LENGTH_USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário deve ter no máximo 50 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_USER_NAME {
            get {
                return ResourceManager.GetString("MAX_LENGTH_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário deve ter no máximo 256 caracteres.
        /// </summary>
        internal static string MAX_LENGTH_USER_PASSWORD {
            get {
                return ResourceManager.GetString("MAX_LENGTH_USER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criação de usuários comuns não é permitida por usuários do tipo {0} (Apenas por Site,  Adm. e Adm. Master).
        /// </summary>
        internal static string other_users_creation_not_allowed_by {
            get {
                return ResourceManager.GetString("other_users_creation_not_allowed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização de usuários comuns não é permitida por usuários do tipo {0} (Apenas por Adm. e Adm. Master).
        /// </summary>
        internal static string other_users_update_not_allowed_by {
            get {
                return ResourceManager.GetString("other_users_update_not_allowed_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial de convocação não pode ser maior que a data final.
        /// </summary>
        internal static string PERIOD_CONVOCATION_INITIAL_DATE_MORETHAN_FINAL_DATE {
            get {
                return ResourceManager.GetString("PERIOD_CONVOCATION_INITIAL_DATE_MORETHAN_FINAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de convocação deve vir antes do período de submissão.
        /// </summary>
        internal static string PERIOD_CONVOCATION_MUST_BEFORE_SUBMISSION {
            get {
                return ResourceManager.GetString("PERIOD_CONVOCATION_MUST_BEFORE_SUBMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um período em aberto.
        /// </summary>
        internal static string PERIOD_HAS_ANOTHER_OPEN {
            get {
                return ResourceManager.GetString("PERIOD_HAS_ANOTHER_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data inicial de submissão não pode ser maior que a data final.
        /// </summary>
        internal static string PERIOD_INITIAL_DATE_MORETHAN_FINAL_DATE {
            get {
                return ResourceManager.GetString("PERIOD_INITIAL_DATE_MORETHAN_FINAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um período cadastrado com a data final de submissão maior que a data inicial informada.
        /// </summary>
        internal static string PERIOD_INVALID_INITIAL_DATE {
            get {
                return ResourceManager.GetString("PERIOD_INVALID_INITIAL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do período está dentro de outro período existente.
        /// </summary>
        internal static string PERIOD_WITH_CONCURRENCE_DATES {
            get {
                return ResourceManager.GetString("PERIOD_WITH_CONCURRENCE_DATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de municípios não permitida.
        /// </summary>
        internal static string request_city_not_allowed {
            get {
                return ResourceManager.GetString("request_city_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação da resposta é obrigatório.
        /// </summary>
        internal static string REQUIRED_ANSWERS_OBSERVATION {
            get {
                return ResourceManager.GetString("REQUIRED_ANSWERS_OBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do bloco base é obrigatório.
        /// </summary>
        internal static string REQUIRED_BASEBLOCK_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_BASEBLOCK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do formulário base é obrigatório.
        /// </summary>
        internal static string REQUIRED_BASEFORM_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_BASEFORM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questão da pergunta base é obrigatória.
        /// </summary>
        internal static string REQUIRED_BASEQUESTION_QUESTION {
            get {
                return ResourceManager.GetString("REQUIRED_BASEQUESTION_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da cidade é obrigatório.
        /// </summary>
        internal static string REQUIRED_CITY_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_CITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da entidade é obrigatório.
        /// </summary>
        internal static string REQUIRED_ENTITY_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_ENTITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do período é obrigatório.
        /// </summary>
        internal static string REQUIRED_PERIOD_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_PERIOD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do estado é obrigatório.
        /// </summary>
        internal static string REQUIRED_STATE_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_STATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações do envio é obrigatório.
        /// </summary>
        internal static string REQUIRED_SUBMIT_OBSERVATION {
            get {
                return ResourceManager.GetString("REQUIRED_SUBMIT_OBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email do usuário é obrigatório.
        /// </summary>
        internal static string REQUIRED_USER_EMAIL {
            get {
                return ResourceManager.GetString("REQUIRED_USER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário é obrigatório.
        /// </summary>
        internal static string REQUIRED_USER_LOGIN {
            get {
                return ResourceManager.GetString("REQUIRED_USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário é obrigatório.
        /// </summary>
        internal static string REQUIRED_USER_NAME {
            get {
                return ResourceManager.GetString("REQUIRED_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login do usuário é obrigatório.
        /// </summary>
        internal static string REQUIRED_USER_PASSWORD {
            get {
                return ResourceManager.GetString("REQUIRED_USER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando aprovação.
        /// </summary>
        internal static string WAITING_APPROVE {
            get {
                return ResourceManager.GetString("WAITING_APPROVE", resourceCulture);
            }
        }
    }
}
