//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Label", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos de uso aceito?.
        /// </summary>
        internal static string accepted_terms {
            get {
                return ResourceManager.GetString("accepted_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciada.
        /// </summary>
        internal static string accredited {
            get {
                return ResourceManager.GetString("accredited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre o endereço.
        /// </summary>
        internal static string address_informations {
            get {
                return ResourceManager.GetString("address_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo colaborador.
        /// </summary>
        internal static string add_a_new_collaborator {
            get {
                return ResourceManager.GetString("add_a_new_collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar uma nova pergunta.
        /// </summary>
        internal static string add_a_new_question {
            get {
                return ResourceManager.GetString("add_a_new_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar um novo sub-bloco.
        /// </summary>
        internal static string add_new_sub_block {
            get {
                return ResourceManager.GetString("add_new_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar pergunta.
        /// </summary>
        internal static string add_question {
            get {
                return ResourceManager.GetString("add_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar sub-bloco.
        /// </summary>
        internal static string add_sub_block {
            get {
                return ResourceManager.GetString("add_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string administrator {
            get {
                return ResourceManager.GetString("administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este questionário já foi publicado!.
        /// </summary>
        internal static string already_published {
            get {
                return ResourceManager.GetString("already_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já classificou este formulário..
        /// </summary>
        internal static string already_rated {
            get {
                return ResourceManager.GetString("already_rated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulários respondidos.
        /// </summary>
        internal static string answered_questions {
            get {
                return ResourceManager.GetString("answered_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        internal static string any {
            get {
                return ResourceManager.GetString("any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum responsável selecionado.
        /// </summary>
        internal static string any_responsable_selected {
            get {
                return ResourceManager.GetString("any_responsable_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado.
        /// </summary>
        internal static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar questionário.
        /// </summary>
        internal static string approve_form {
            get {
                return ResourceManager.GetString("approve_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar questionário.
        /// </summary>
        internal static string approve_question {
            get {
                return ResourceManager.GetString("approve_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhamento dos cálculos.
        /// </summary>
        internal static string calculation_details {
            get {
                return ResourceManager.GetString("calculation_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municípios.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações do município.
        /// </summary>
        internal static string city_informations {
            get {
                return ResourceManager.GetString("city_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do município.
        /// </summary>
        internal static string city_name {
            get {
                return ResourceManager.GetString("city_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechado.
        /// </summary>
        internal static string closed {
            get {
                return ResourceManager.GetString("closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        internal static string cnpj {
            get {
                return ResourceManager.GetString("cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador.
        /// </summary>
        internal static string collaborator {
            get {
                return ResourceManager.GetString("collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string collaborators {
            get {
                return ResourceManager.GetString("collaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador nas cidades.
        /// </summary>
        internal static string collaborator_by_cities {
            get {
                return ResourceManager.GetString("collaborator_by_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários comuns.
        /// </summary>
        internal static string common_users {
            get {
                return ResourceManager.GetString("common_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações de contato.
        /// </summary>
        internal static string contact_informations {
            get {
                return ResourceManager.GetString("contact_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de convocação.
        /// </summary>
        internal static string convocation_period {
            get {
                return ResourceManager.GetString("convocation_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar formulário.
        /// </summary>
        internal static string copy_form {
            get {
                return ResourceManager.GetString("copy_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar a partir.
        /// </summary>
        internal static string copy_form_from {
            get {
                return ResourceManager.GetString("copy_form_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar um novo questionário.
        /// </summary>
        internal static string create_a_new_baseform {
            get {
                return ResourceManager.GetString("create_a_new_baseform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar um novo município.
        /// </summary>
        internal static string create_a_new_city {
            get {
                return ResourceManager.GetString("create_a_new_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar um novo período.
        /// </summary>
        internal static string create_a_new_period {
            get {
                return ResourceManager.GetString("create_a_new_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar um novo usuário.
        /// </summary>
        internal static string create_a_new_user {
            get {
                return ResourceManager.GetString("create_a_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar um novo período.
        /// </summary>
        internal static string create_new_period {
            get {
                return ResourceManager.GetString("create_new_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de controle.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar pergunta.
        /// </summary>
        internal static string delete_question {
            get {
                return ResourceManager.GetString("delete_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar sub-bloco.
        /// </summary>
        internal static string delete_sub_block {
            get {
                return ResourceManager.GetString("delete_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desejo criar um novo questionário.
        /// </summary>
        internal static string desire_create_a_new_form {
            get {
                return ResourceManager.GetString("desire_create_a_new_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desejo criar a partir de um questionário existente.
        /// </summary>
        internal static string desire_create_from_another_form {
            get {
                return ResourceManager.GetString("desire_create_from_another_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvido por.
        /// </summary>
        internal static string develop_by {
            get {
                return ResourceManager.GetString("develop_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativos.
        /// </summary>
        internal static string disables {
            get {
                return ResourceManager.GetString("disables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efetuar Login.
        /// </summary>
        internal static string do_login {
            get {
                return ResourceManager.GetString("do_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar nome do questionário.
        /// </summary>
        internal static string edit_form_name {
            get {
                return ResourceManager.GetString("edit_form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        internal static string edit_profile {
            get {
                return ResourceManager.GetString("edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar pergunta.
        /// </summary>
        internal static string edit_question {
            get {
                return ResourceManager.GetString("edit_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar sub-bloco.
        /// </summary>
        internal static string edit_sub_block {
            get {
                return ResourceManager.GetString("edit_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativos.
        /// </summary>
        internal static string enables {
            get {
                return ResourceManager.GetString("enables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string entities {
            get {
                return ResourceManager.GetString("entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        internal static string entity {
            get {
                return ResourceManager.GetString("entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da entidade.
        /// </summary>
        internal static string entity_name {
            get {
                return ResourceManager.GetString("entity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade credenciada aprovada?.
        /// </summary>
        internal static string entity_network_approved {
            get {
                return ResourceManager.GetString("entity_network_approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saindo....
        /// </summary>
        internal static string exiting {
            get {
                return ResourceManager.GetString("exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocação final.
        /// </summary>
        internal static string final_convocation_date {
            get {
                return ResourceManager.GetString("final_convocation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final.
        /// </summary>
        internal static string final_date {
            get {
                return ResourceManager.GetString("final_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final do período.
        /// </summary>
        internal static string final_date_period {
            get {
                return ResourceManager.GetString("final_date_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissão final.
        /// </summary>
        internal static string final_submission_date {
            get {
                return ResourceManager.GetString("final_submission_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionário.
        /// </summary>
        internal static string form {
            get {
                return ResourceManager.GetString("form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação de questionários.
        /// </summary>
        internal static string form_reviews {
            get {
                return ResourceManager.GetString("form_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações gerais.
        /// </summary>
        internal static string general_informations {
            get {
                return ResourceManager.GetString("general_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convocação inicial.
        /// </summary>
        internal static string initial_convocation_date {
            get {
                return ResourceManager.GetString("initial_convocation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial.
        /// </summary>
        internal static string initial_date {
            get {
                return ResourceManager.GetString("initial_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial do período.
        /// </summary>
        internal static string initial_date_period {
            get {
                return ResourceManager.GetString("initial_date_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissão inicial.
        /// </summary>
        internal static string initial_submission_date {
            get {
                return ResourceManager.GetString("initial_submission_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira sua senha.
        /// </summary>
        internal static string insert_your_password {
            get {
                return ResourceManager.GetString("insert_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira seu usuário.
        /// </summary>
        internal static string insert_your_user {
            get {
                return ResourceManager.GetString("insert_your_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail institucional.
        /// </summary>
        internal static string institutional_email {
            get {
                return ResourceManager.GetString("institutional_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (de {1:dd/MM/yyyy} até {2:dd/MM/yyyy}).
        /// </summary>
        internal static string list_item_period_label {
            get {
                return ResourceManager.GetString("list_item_period_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando os municípios.
        /// </summary>
        internal static string loading_cities {
            get {
                return ResourceManager.GetString("loading_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando os períodos....
        /// </summary>
        internal static string loading_periods {
            get {
                return ResourceManager.GetString("loading_periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando usuários....
        /// </summary>
        internal static string loading_users {
            get {
                return ResourceManager.GetString("loading_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre acesso.
        /// </summary>
        internal static string login_informations {
            get {
                return ResourceManager.GetString("login_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradores.
        /// </summary>
        internal static string managers {
            get {
                return ResourceManager.GetString("managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de municípios.
        /// </summary>
        internal static string manage_cities {
            get {
                return ResourceManager.GetString("manage_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de município.
        /// </summary>
        internal static string manage_city {
            get {
                return ResourceManager.GetString("manage_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar questionários.
        /// </summary>
        internal static string manage_form {
            get {
                return ResourceManager.GetString("manage_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de períodos.
        /// </summary>
        internal static string manage_periods {
            get {
                return ResourceManager.GetString("manage_periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação de questionários.
        /// </summary>
        internal static string manage_response_form {
            get {
                return ResourceManager.GetString("manage_response_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar usuários.
        /// </summary>
        internal static string manage_users {
            get {
                return ResourceManager.GetString("manage_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminstrador Master.
        /// </summary>
        internal static string master {
            get {
                return ResourceManager.GetString("master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período {0}.
        /// </summary>
        internal static string menu_period {
            get {
                return ResourceManager.GetString("menu_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natureza.
        /// </summary>
        internal static string nature {
            get {
                return ResourceManager.GetString("nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string neighborhood {
            get {
                return ResourceManager.GetString("neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo administrador.
        /// </summary>
        internal static string new_admin {
            get {
                return ResourceManager.GetString("new_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo município.
        /// </summary>
        internal static string new_city {
            get {
                return ResourceManager.GetString("new_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo usuário comum.
        /// </summary>
        internal static string new_common {
            get {
                return ResourceManager.GetString("new_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova entidade.
        /// </summary>
        internal static string new_entity {
            get {
                return ResourceManager.GetString("new_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo período.
        /// </summary>
        internal static string new_period {
            get {
                return ResourceManager.GetString("new_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo usuário.
        /// </summary>
        internal static string new_user {
            get {
                return ResourceManager.GetString("new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum colaborador.
        /// </summary>
        internal static string no_collaborator {
            get {
                return ResourceManager.GetString("no_collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum questionário encontrado para esse período.
        /// </summary>
        internal static string no_form_founded_for_this_period {
            get {
                return ResourceManager.GetString("no_form_founded_for_this_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem responsável.
        /// </summary>
        internal static string no_responsable {
            get {
                return ResourceManager.GetString("no_responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma classificação realizada..
        /// </summary>
        internal static string no_reviews {
            get {
                return ResourceManager.GetString("no_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações.
        /// </summary>
        internal static string observations {
            get {
                return ResourceManager.GetString("observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberto.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de atuação.
        /// </summary>
        internal static string operation_area {
            get {
                return ResourceManager.GetString("operation_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrangência de atuação.
        /// </summary>
        internal static string operation_range {
            get {
                return ResourceManager.GetString("operation_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organização.
        /// </summary>
        internal static string organization {
            get {
                return ResourceManager.GetString("organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da organização.
        /// </summary>
        internal static string organization_name {
            get {
                return ResourceManager.GetString("organization_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail do representante.
        /// </summary>
        internal static string organization_representative_email {
            get {
                return ResourceManager.GetString("organization_representative_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do representante da organização.
        /// </summary>
        internal static string organization_representative_name {
            get {
                return ResourceManager.GetString("organization_representative_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        internal static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período já publicado..
        /// </summary>
        internal static string period_already_published {
            get {
                return ResourceManager.GetString("period_already_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este período não pode ser publicado..
        /// </summary>
        internal static string period_couldnt_be_published {
            get {
                return ResourceManager.GetString("period_couldnt_be_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período está aberto, portanto o questionário não pode ser editado.
        /// </summary>
        internal static string period_is_open_so_cannot_be_edited {
            get {
                return ResourceManager.GetString("period_is_open_so_cannot_be_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de períodos.
        /// </summary>
        internal static string period_list {
            get {
                return ResourceManager.GetString("period_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de período.
        /// </summary>
        internal static string period_register {
            get {
                return ResourceManager.GetString("period_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do período.
        /// </summary>
        internal static string period_status {
            get {
                return ResourceManager.GetString("period_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto de perfil.
        /// </summary>
        internal static string profile_photo {
            get {
                return ResourceManager.GetString("profile_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar.
        /// </summary>
        internal static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar período.
        /// </summary>
        internal static string publish_period {
            get {
                return ResourceManager.GetString("publish_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar questionário.
        /// </summary>
        internal static string publish_question {
            get {
                return ResourceManager.GetString("publish_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar questionários.
        /// </summary>
        internal static string publish_questions {
            get {
                return ResourceManager.GetString("publish_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ao concordar em publicar o período, todos os questionários respondidos que tiveram a submissão aceita irão ser publicados no site. Sendo assim, não será possível desfazer essa ação..
        /// </summary>
        internal static string publish_questions_terms1 {
            get {
                return ResourceManager.GetString("publish_questions_terms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você tem certeza que deseja publicar o período?.
        /// </summary>
        internal static string publish_questions_terms2 {
            get {
                return ResourceManager.GetString("publish_questions_terms2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publicar questionários selecionados.
        /// </summary>
        internal static string publish_selected_questions {
            get {
                return ResourceManager.GetString("publish_selected_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovo que esta entidade é credenciada?.
        /// </summary>
        internal static string question_approve_that_this_entity_is_accredited {
            get {
                return ResourceManager.GetString("question_approve_that_this_entity_is_accredited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do questionário.
        /// </summary>
        internal static string question_name {
            get {
                return ResourceManager.GetString("question_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está entidade é credenciada?.
        /// </summary>
        internal static string question_this_entity_is_accredited {
            get {
                return ResourceManager.GetString("question_this_entity_is_accredited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificar.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região.
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  registro(s) encontrado(s).
        /// </summary>
        internal static string registers_founded {
            get {
                return ResourceManager.GetString("registers_founded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar um novo período.
        /// </summary>
        internal static string register_a_new_period {
            get {
                return ResourceManager.GetString("register_a_new_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de cadastro.
        /// </summary>
        internal static string register_type {
            get {
                return ResourceManager.GetString("register_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar pergunta.
        /// </summary>
        internal static string remove_question {
            get {
                return ResourceManager.GetString("remove_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar sub-bloco.
        /// </summary>
        internal static string remove_sub_block {
            get {
                return ResourceManager.GetString("remove_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovar questionário.
        /// </summary>
        internal static string repprove_form {
            get {
                return ResourceManager.GetString("repprove_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovar.
        /// </summary>
        internal static string reprove {
            get {
                return ResourceManager.GetString("reprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovado.
        /// </summary>
        internal static string reproved {
            get {
                return ResourceManager.GetString("reproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovar formulário.
        /// </summary>
        internal static string reprove_question {
            get {
                return ResourceManager.GetString("reprove_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitações pendentes.
        /// </summary>
        internal static string requests_pending {
            get {
                return ResourceManager.GetString("requests_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string request_a_city {
            get {
                return ResourceManager.GetString("request_a_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de municípios.
        /// </summary>
        internal static string request_cities {
            get {
                return ResourceManager.GetString("request_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Município solicitado.
        /// </summary>
        internal static string request_city {
            get {
                return ResourceManager.GetString("request_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da solicitação.
        /// </summary>
        internal static string request_date {
            get {
                return ResourceManager.GetString("request_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        internal static string request_status {
            get {
                return ResourceManager.GetString("request_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de solicitação.
        /// </summary>
        internal static string request_type {
            get {
                return ResourceManager.GetString("request_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string responsable {
            get {
                return ResourceManager.GetString("responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável pelas cidades.
        /// </summary>
        internal static string responsable_by_cities {
            get {
                return ResourceManager.GetString("responsable_by_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do responsável.
        /// </summary>
        internal static string responsable_name {
            get {
                return ResourceManager.GetString("responsable_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classificações.
        /// </summary>
        internal static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da classificação.
        /// </summary>
        internal static string review_date {
            get {
                return ResourceManager.GetString("review_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionado para publicar.
        /// </summary>
        internal static string selected_to_published {
            get {
                return ResourceManager.GetString("selected_to_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        internal static string select_an_item {
            get {
                return ResourceManager.GetString("select_an_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um colaborador.
        /// </summary>
        internal static string select_a_collaborator {
            get {
                return ResourceManager.GetString("select_a_collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da submissão.
        /// </summary>
        internal static string submision_status {
            get {
                return ResourceManager.GetString("submision_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submissões.
        /// </summary>
        internal static string submissions {
            get {
                return ResourceManager.GetString("submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da submissão.
        /// </summary>
        internal static string submission_date {
            get {
                return ResourceManager.GetString("submission_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de submissão.
        /// </summary>
        internal static string submission_period {
            get {
                return ResourceManager.GetString("submission_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submetido.
        /// </summary>
        internal static string submitted {
            get {
                return ResourceManager.GetString("submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta entidade não é credenciada.
        /// </summary>
        internal static string this_entity_isnt_accredited {
            get {
                return ResourceManager.GetString("this_entity_isnt_accredited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to até.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de colaboradores.
        /// </summary>
        internal static string total_of_collaborators {
            get {
                return ResourceManager.GetString("total_of_collaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferramenta de transparência.
        /// </summary>
        internal static string transparency_tool {
            get {
                return ResourceManager.GetString("transparency_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do usuário.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuário.
        /// </summary>
        internal static string usertype {
            get {
                return ResourceManager.GetString("usertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários comuns.
        /// </summary>
        internal static string user_comum {
            get {
                return ResourceManager.GetString("user_comum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do usuário.
        /// </summary>
        internal static string user_status {
            get {
                return ResourceManager.GetString("user_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar formulários que serão publicados..
        /// </summary>
        internal static string visualize_questions_tobe_published {
            get {
                return ResourceManager.GetString("visualize_questions_tobe_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde....
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguardando aprovação.
        /// </summary>
        internal static string waiting_approve {
            get {
                return ResourceManager.GetString("waiting_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem filtro.
        /// </summary>
        internal static string withou_filter {
            get {
                return ResourceManager.GetString("withou_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep.
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
