//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovado por.
        /// </summary>
        internal static string approved_by {
            get {
                return ResourceManager.GetString("approved_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking dos cálculos..
        /// </summary>
        internal static string calculate_tracking {
            get {
                return ResourceManager.GetString("calculate_tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do município é obrigatório.
        /// </summary>
        internal static string city_name_is_mandatory {
            get {
                return ResourceManager.GetString("city_name_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui caso queira voltar para lista.
        /// </summary>
        internal static string click_here_if_you_want_back_to_the_list {
            get {
                return ResourceManager.GetString("click_here_if_you_want_back_to_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não conseguimos processar seu pedido.
        /// </summary>
        internal static string couldnt_process_request {
            get {
                return ResourceManager.GetString("couldnt_process_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail informado está em uso.
        /// </summary>
        internal static string email_already_used {
            get {
                return ResourceManager.GetString("email_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um período aberto de &lt;strong&gt;{0:dd/MM/yyyy}&lt;/strong&gt; até &lt;strong&gt;{1:dd/MM/yyyy}&lt;/strong&gt;.
        /// </summary>
        internal static string exists_an_open_period_from_to {
            get {
                return ResourceManager.GetString("exists_an_open_period_from_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário &apos;{0}&apos; foi criado com sucesso!, {1}.
        /// </summary>
        internal static string format_user_has_been_created_with_success {
            get {
                return ResourceManager.GetString("format_user_has_been_created_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário &apos;{0}&apos; foi atualizado com sucesso!, {1}.
        /// </summary>
        internal static string format_user_has_been_updated_with_success {
            get {
                return ResourceManager.GetString("format_user_has_been_updated_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionário copiado com sucesso.
        /// </summary>
        internal static string form_copied_with_success {
            get {
                return ResourceManager.GetString("form_copied_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira um nome para o sub-bloco.
        /// </summary>
        internal static string insert_a_name_for_sub_block {
            get {
                return ResourceManager.GetString("insert_a_name_for_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira uma pergunta.
        /// </summary>
        internal static string insert_a_question {
            get {
                return ResourceManager.GetString("insert_a_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insira um peso para o sub-bloco.
        /// </summary>
        internal static string insert_a_weight_for_sub_block {
            get {
                return ResourceManager.GetString("insert_a_weight_for_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre com o seu usuário e senha.
        /// </summary>
        internal static string insert_your_login_and_password {
            get {
                return ResourceManager.GetString("insert_your_login_and_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem inválida (Tipos aceitos .bmp, .jpg, .jpeg e .png).
        /// </summary>
        internal static string invalid_image_extension {
            get {
                return ResourceManager.GetString("invalid_image_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deixar em branco caso não queira atualizar.
        /// </summary>
        internal static string leave_this_box_blank {
            get {
                return ResourceManager.GetString("leave_this_box_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login informado está em uso.
        /// </summary>
        internal static string login_already_used {
            get {
                return ResourceManager.GetString("login_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login/Senha precisam ser preenchidos.
        /// </summary>
        internal static string login_password_must_be_filled {
            get {
                return ResourceManager.GetString("login_password_must_be_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve-se criar um período com a data posterior a &lt;strong&gt;{0:dd/MM/yyyy}&lt;/strong&gt;.
        /// </summary>
        internal static string need_create_period_from {
            get {
                return ResourceManager.GetString("need_create_period_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum período encontrado.
        /// </summary>
        internal static string no_period_has_found {
            get {
                return ResourceManager.GetString("no_period_has_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string observation {
            get {
                return ResourceManager.GetString("observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro obrigatório não informado.
        /// </summary>
        internal static string parameter_not_found {
            get {
                return ResourceManager.GetString("parameter_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do período não encontrado.
        /// </summary>
        internal static string period_id_not_found {
            get {
                return ResourceManager.GetString("period_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período não encontrado.
        /// </summary>
        internal static string period_not_found {
            get {
                return ResourceManager.GetString("period_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao adicionar um pergunta.
        /// </summary>
        internal static string problem_to_add_a_question {
            get {
                return ResourceManager.GetString("problem_to_add_a_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao adicionar um sub-bloco.
        /// </summary>
        internal static string problem_to_add_a_sub_block {
            get {
                return ResourceManager.GetString("problem_to_add_a_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao carregar a cidade requisitada.
        /// </summary>
        internal static string problem_to_load_requested_city {
            get {
                return ResourceManager.GetString("problem_to_load_requested_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel carregar o usuário solicitado.
        /// </summary>
        internal static string problem_to_load_requested_user {
            get {
                return ResourceManager.GetString("problem_to_load_requested_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao copiar o formulário.
        /// </summary>
        internal static string problem_when_copied_form {
            get {
                return ResourceManager.GetString("problem_when_copied_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao remover uma pergunta.
        /// </summary>
        internal static string problem_when_remove_a_question {
            get {
                return ResourceManager.GetString("problem_when_remove_a_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema ao remover um sub-bloco.
        /// </summary>
        internal static string problem_when_remove_a_sub_block {
            get {
                return ResourceManager.GetString("problem_when_remove_a_sub_block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta adicionada com sucesso.
        /// </summary>
        internal static string question_added_with_success {
            get {
                return ResourceManager.GetString("question_added_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta removida com sucesso.
        /// </summary>
        internal static string question_deleted_with_success {
            get {
                return ResourceManager.GetString("question_deleted_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta atualizada com sucesso.
        /// </summary>
        internal static string question_updated_with_success {
            get {
                return ResourceManager.GetString("question_updated_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string request_a_city {
            get {
                return ResourceManager.GetString("request_a_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área restrita, entre em contato com o seu administrador..
        /// </summary>
        internal static string restrict_page_message {
            get {
                return ResourceManager.GetString("restrict_page_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-bloco criado com sucesso.
        /// </summary>
        internal static string sub_block_added_with_success {
            get {
                return ResourceManager.GetString("sub_block_added_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-bloco removido com sucesso.
        /// </summary>
        internal static string sub_block_deleted_with_success {
            get {
                return ResourceManager.GetString("sub_block_deleted_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-bloco atualizado com sucesso.
        /// </summary>
        internal static string sub_block_updated_with_success {
            get {
                return ResourceManager.GetString("sub_block_updated_with_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este questionário já foi aprovado para publicação.
        /// </summary>
        internal static string this_form_has_been_approved_to_published {
            get {
                return ResourceManager.GetString("this_form_has_been_approved_to_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuário ainda não aceitou os termos de uso.
        /// </summary>
        internal static string this_user_not_accepted_the_terms {
            get {
                return ResourceManager.GetString("this_user_not_accepted_the_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops...Desculpa, mas não conseguimos processar sua solicitacão - Erro: {0}.
        /// </summary>
        internal static string unknow_error {
            get {
                return ResourceManager.GetString("unknow_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não autorizado.
        /// </summary>
        internal static string user_not_allowed {
            get {
                return ResourceManager.GetString("user_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuário obrigatório.
        /// </summary>
        internal static string user_type_is_mandatory {
            get {
                return ResourceManager.GetString("user_type_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar questionário.
        /// </summary>
        internal static string view_questions {
            get {
                return ResourceManager.GetString("view_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Será criado um novo questionário e todos os blocos e perguntas do questionário serão copiados, deseja continuar? Esse processo é irreversível..
        /// </summary>
        internal static string will_be_create_a_new_form {
            get {
                return ResourceManager.GetString("will_be_create_a_new_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já inseriu uma classificação para este questionário.
        /// </summary>
        internal static string you_already_add_a_review {
            get {
                return ResourceManager.GetString("you_already_add_a_review", resourceCulture);
            }
        }
    }
}
