//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quem somos.
        /// </summary>
        internal static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceito.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceito os termos de uso.
        /// </summary>
        internal static string accept_terms {
            get {
                return ResourceManager.GetString("accept_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre acesso.
        /// </summary>
        internal static string access_information {
            get {
                return ResourceManager.GetString("access_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações sobre o endereço.
        /// </summary>
        internal static string address_information {
            get {
                return ResourceManager.GetString("address_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar observações.
        /// </summary>
        internal static string add_observations {
            get {
                return ResourceManager.GetString("add_observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa aceitar os termos de uso.
        /// </summary>
        internal static string agree_terms {
            get {
                return ResourceManager.GetString("agree_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estou de acordo com os termos de uso.
        /// </summary>
        internal static string agree_with_terms {
            get {
                return ResourceManager.GetString("agree_with_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder.
        /// </summary>
        internal static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionário respondidos.
        /// </summary>
        internal static string answer_form {
            get {
                return ResourceManager.GetString("answer_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o questionário e compare com o Ranking atual.
        /// </summary>
        internal static string answer_form_and_compare {
            get {
                return ResourceManager.GetString("answer_form_and_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responda o questionário.
        /// </summary>
        internal static string answer_name {
            get {
                return ResourceManager.GetString("answer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencher offline.
        /// </summary>
        internal static string answer_offline {
            get {
                return ResourceManager.GetString("answer_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencher online.
        /// </summary>
        internal static string answer_online {
            get {
                return ResourceManager.GetString("answer_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responder questionário.
        /// </summary>
        internal static string answer_question {
            get {
                return ResourceManager.GetString("answer_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responda o questionário.
        /// </summary>
        internal static string answer_value {
            get {
                return ResourceManager.GetString("answer_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você tem certeza que deseja submeter esse questionário?.
        /// </summary>
        internal static string are_you_sure_submit_form {
            get {
                return ResourceManager.GetString("are_you_sure_submit_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boas práticas.
        /// </summary>
        internal static string best_pratices {
            get {
                return ResourceManager.GetString("best_pratices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking dos cálculos..
        /// </summary>
        internal static string calculate_tracking {
            get {
                return ResourceManager.GetString("calculate_tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municípios.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Município.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado e a cidade.
        /// </summary>
        internal static string city_name {
            get {
                return ResourceManager.GetString("city_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Município não informado.
        /// </summary>
        internal static string city_not_selected {
            get {
                return ResourceManager.GetString("city_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, informe a cidade avaliada.
        /// </summary>
        internal static string city_not_selected_to_available {
            get {
                return ResourceManager.GetString("city_not_selected_to_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado/cidade do formulário.
        /// </summary>
        internal static string city_state_form {
            get {
                return ResourceManager.GetString("city_state_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o estado e a cidade responsável pelo questionário..
        /// </summary>
        internal static string city_value {
            get {
                return ResourceManager.GetString("city_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clicando aqui.
        /// </summary>
        internal static string click_here {
            get {
                return ResourceManager.GetString("click_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui.
        /// </summary>
        internal static string click_here2 {
            get {
                return ResourceManager.GetString("click_here2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para responder o questionário.
        /// </summary>
        internal static string click_here_and_form {
            get {
                return ResourceManager.GetString("click_here_and_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cnpj.
        /// </summary>
        internal static string cnpj {
            get {
                return ResourceManager.GetString("cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaboradores.
        /// </summary>
        internal static string collaborators {
            get {
                return ResourceManager.GetString("collaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comum.
        /// </summary>
        internal static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completos.
        /// </summary>
        internal static string complete_forms {
            get {
                return ResourceManager.GetString("complete_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar senha.
        /// </summary>
        internal static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabéns você concluiu o preenchimento do questionário.
        /// </summary>
        internal static string congratulations_form_was_finished {
            get {
                return ResourceManager.GetString("congratulations_form_was_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabéns!! Seu questionário está corretamente preenchido e aprovado.
        /// </summary>
        internal static string congratulations_your_form_has_been_filled {
            get {
                return ResourceManager.GetString("congratulations_your_form_has_been_filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parabéns!! Seu questionário está corretamente preenchido e foi submetido para aprovação.
        /// </summary>
        internal static string congratulations_your_form_has_been_filled_and_submited {
            get {
                return ResourceManager.GetString("congratulations_your_form_has_been_filled_and_submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações de contato.
        /// </summary>
        internal static string contact_information {
            get {
                return ResourceManager.GetString("contact_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar município.
        /// </summary>
        internal static string do_request_city {
            get {
                return ResourceManager.GetString("do_request_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar perfil.
        /// </summary>
        internal static string edit_profile {
            get {
                return ResourceManager.GetString("edit_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string entities {
            get {
                return ResourceManager.GetString("entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidade.
        /// </summary>
        internal static string entity {
            get {
                return ResourceManager.GetString("entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a entidade.
        /// </summary>
        internal static string entity_name {
            get {
                return ResourceManager.GetString("entity_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da entidade.
        /// </summary>
        internal static string entity_name_ {
            get {
                return ResourceManager.GetString("entity_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a entidade responsável pelo questionário..
        /// </summary>
        internal static string entity_value {
            get {
                return ResourceManager.GetString("entity_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já existe.
        /// </summary>
        internal static string exists_email {
            get {
                return ResourceManager.GetString("exists_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário já existe.
        /// </summary>
        internal static string exists_login {
            get {
                return ResourceManager.GetString("exists_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar questionário.
        /// </summary>
        internal static string export_form {
            get {
                return ResourceManager.GetString("export_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporte o questionário.
        /// </summary>
        internal static string export_name {
            get {
                return ResourceManager.GetString("export_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporte o questionário.
        /// </summary>
        internal static string export_value {
            get {
                return ResourceManager.GetString("export_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o arquivo respondido.
        /// </summary>
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o arquivo que você respondeu..
        /// </summary>
        internal static string file_value {
            get {
                return ResourceManager.GetString("file_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha o questionário e compare com o Ranking atual.
        /// </summary>
        internal static string fill_form_and_compare {
            get {
                return ResourceManager.GetString("fill_form_and_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        internal static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionário.
        /// </summary>
        internal static string form {
            get {
                return ResourceManager.GetString("form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu questionário não foi aprovado, por favor revise e submeta novamente..
        /// </summary>
        internal static string form_must_revised {
            get {
                return ResourceManager.GetString("form_must_revised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do questionário.
        /// </summary>
        internal static string form_name {
            get {
                return ResourceManager.GetString("form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este questionário será publicado.
        /// </summary>
        internal static string form_will_be_published {
            get {
                return ResourceManager.GetString("form_will_be_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 0 até 20%.
        /// </summary>
        internal static string from_0_to_20 {
            get {
                return ResourceManager.GetString("from_0_to_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 20 até 40%.
        /// </summary>
        internal static string from_20_to_40 {
            get {
                return ResourceManager.GetString("from_20_to_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 40 até 60%.
        /// </summary>
        internal static string from_40_to_60 {
            get {
                return ResourceManager.GetString("from_40_to_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 60 até 80%.
        /// </summary>
        internal static string from_60_to_80 {
            get {
                return ResourceManager.GetString("from_60_to_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de 80 até 100%.
        /// </summary>
        internal static string from_80_to_100 {
            get {
                return ResourceManager.GetString("from_80_to_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string from_NA_to_NA {
            get {
                return ResourceManager.GetString("from_NA_to_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações gerais.
        /// </summary>
        internal static string general_informations {
            get {
                return ResourceManager.GetString("general_informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boas Práticas.
        /// </summary>
        internal static string good_praticies {
            get {
                return ResourceManager.GetString("good_praticies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como participar.
        /// </summary>
        internal static string how_to_participate {
            get {
                return ResourceManager.GetString("how_to_participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como você prefere preencher o questionário?.
        /// </summary>
        internal static string how_to_prefer_fill_the_form {
            get {
                return ResourceManager.GetString("how_to_prefer_fill_the_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sou uma organização credenciada.
        /// </summary>
        internal static string iam_accredited_entity {
            get {
                return ResourceManager.GetString("iam_accredited_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sou uma entidade.
        /// </summary>
        internal static string iam_an_entity_user {
            get {
                return ResourceManager.GetString("iam_an_entity_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sou um usuário comum.
        /// </summary>
        internal static string iam_a_common_user {
            get {
                return ResourceManager.GetString("iam_a_common_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar questionário.
        /// </summary>
        internal static string import_form {
            get {
                return ResourceManager.GetString("import_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompletos.
        /// </summary>
        internal static string incomplete_forms {
            get {
                return ResourceManager.GetString("incomplete_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Índice.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu CNPJ.
        /// </summary>
        internal static string input_your_cnpj {
            get {
                return ResourceManager.GetString("input_your_cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu e-mail.
        /// </summary>
        internal static string input_your_email {
            get {
                return ResourceManager.GetString("input_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite sua senha.
        /// </summary>
        internal static string input_your_password {
            get {
                return ResourceManager.GetString("input_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite seu usuário.
        /// </summary>
        internal static string input_your_user {
            get {
                return ResourceManager.GetString("input_your_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sessão.
        /// </summary>
        internal static string insert_session {
            get {
                return ResourceManager.GetString("insert_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem inválida (Tipos aceitos .bmp, .jpg, .jpeg e .png).
        /// </summary>
        internal static string invalid_image_extension {
            get {
                return ResourceManager.GetString("invalid_image_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desejo ser &lt;strong&gt;colaborador&lt;/strong&gt; deste município.
        /// </summary>
        internal static string I_will_be_the_collaborator {
            get {
                return ResourceManager.GetString("I_will_be_the_collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desejo ser &lt;strong&gt;responsável&lt;/strong&gt; deste município.
        /// </summary>
        internal static string I_will_be_the_responsable {
            get {
                return ResourceManager.GetString("I_will_be_the_responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legenda: .
        /// </summary>
        internal static string legend {
            get {
                return ResourceManager.GetString("legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando questionários....
        /// </summary>
        internal static string loading_forms {
            get {
                return ResourceManager.GetString("loading_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodologia.
        /// </summary>
        internal static string methodology {
            get {
                return ResourceManager.GetString("methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus questionários.
        /// </summary>
        internal static string my_forms {
            get {
                return ResourceManager.GetString("my_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da cidade.
        /// </summary>
        internal static string name_of_city {
            get {
                return ResourceManager.GetString("name_of_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natureza.
        /// </summary>
        internal static string nature {
            get {
                return ResourceManager.GetString("nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        internal static string neighborhood {
            get {
                return ResourceManager.GetString("neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosseguir.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhum questionário disponível para download.
        /// </summary>
        internal static string no_question {
            get {
                return ResourceManager.GetString("no_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem resposta.
        /// </summary>
        internal static string no_response {
            get {
                return ResourceManager.GetString("no_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ainda não possuí questionários enviados.
        /// </summary>
        internal static string no_row_forms {
            get {
                return ResourceManager.GetString("no_row_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação.
        /// </summary>
        internal static string observation {
            get {
                return ResourceManager.GetString("observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo offline.
        /// </summary>
        internal static string offline_mode {
            get {
                return ResourceManager.GetString("offline_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso queira preecher o questionário offline ou importar um questionário já preenchido, clique abaixo para prosseguir com o preenchimento..
        /// </summary>
        internal static string offline_mode_message {
            get {
                return ResourceManager.GetString("offline_mode_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo online.
        /// </summary>
        internal static string online_mode {
            get {
                return ResourceManager.GetString("online_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caso queira preecher o questionário online ou continuar o preenchimento de onde parou, selecione abaixo o município e prossiga com o preenchimento..
        /// </summary>
        internal static string online_mode_message {
            get {
                return ResourceManager.GetString("online_mode_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de atuação.
        /// </summary>
        internal static string operation_area {
            get {
                return ResourceManager.GetString("operation_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrangência de atuação.
        /// </summary>
        internal static string operation_range {
            get {
                return ResourceManager.GetString("operation_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações da organização.
        /// </summary>
        internal static string organization_information {
            get {
                return ResourceManager.GetString("organization_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametro obrigatório não informado.
        /// </summary>
        internal static string parameter_not_found {
            get {
                return ResourceManager.GetString("parameter_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        internal static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Períodos.
        /// </summary>
        internal static string periods {
            get {
                return ResourceManager.GetString("periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período aberto para avaliação.
        /// </summary>
        internal static string period_open_to_avail {
            get {
                return ResourceManager.GetString("period_open_to_avail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        internal static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        internal static string pointing {
            get {
                return ResourceManager.GetString("pointing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro ao tentar reenviar sua senha, por favor entre em contato com o administrador..
        /// </summary>
        internal static string problem_to_send_your_passoword {
            get {
                return ResourceManager.GetString("problem_to_send_your_passoword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar senha.
        /// </summary>
        internal static string recover_password {
            get {
                return ResourceManager.GetString("recover_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Região.
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail do representante da organização.
        /// </summary>
        internal static string representant_email {
            get {
                return ResourceManager.GetString("representant_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do representante da organização.
        /// </summary>
        internal static string representant_name {
            get {
                return ResourceManager.GetString("representant_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidades solicitadas.
        /// </summary>
        internal static string requesteds_cityname {
            get {
                return ResourceManager.GetString("requesteds_cityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade solicitada.
        /// </summary>
        internal static string requested_cityname {
            get {
                return ResourceManager.GetString("requested_cityname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitações de cidades.
        /// </summary>
        internal static string request_cities {
            get {
                return ResourceManager.GetString("request_cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Solicitação de município poderá ser feita até o dia {0:dd/MM/yyyy}.
        /// </summary>
        internal static string request_cities_may_be_until {
            get {
                return ResourceManager.GetString("request_cities_may_be_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar um município para avaliar.
        /// </summary>
        internal static string request_city {
            get {
                return ResourceManager.GetString("request_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da solicitação.
        /// </summary>
        internal static string request_status {
            get {
                return ResourceManager.GetString("request_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de solicitação.
        /// </summary>
        internal static string request_type {
            get {
                return ResourceManager.GetString("request_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        internal static string responsable {
            get {
                return ResourceManager.GetString("responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área restrita, entre em contato com o seu administrador..
        /// </summary>
        internal static string restrict_page_message {
            get {
                return ResourceManager.GetString("restrict_page_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalhes do questionário.
        /// </summary>
        internal static string see_form_details {
            get {
                return ResourceManager.GetString("see_form_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionado para publicar.
        /// </summary>
        internal static string selected_to_published {
            get {
                return ResourceManager.GetString("selected_to_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        internal static string select_an_item {
            get {
                return ResourceManager.GetString("select_an_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione a cidade avaliada.
        /// </summary>
        internal static string select_a_city {
            get {
                return ResourceManager.GetString("select_a_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um cidade.
        /// </summary>
        internal static string select_a_city1 {
            get {
                return ResourceManager.GetString("select_a_city1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um estado.
        /// </summary>
        internal static string select_a_state {
            get {
                return ResourceManager.GetString("select_a_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionários já enviados.
        /// </summary>
        internal static string sent_questions {
            get {
                return ResourceManager.GetString("sent_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe, mas não encontramos a página solicitada..
        /// </summary>
        internal static string sorry_page_not_found {
            get {
                return ResourceManager.GetString("sorry_page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sessão.
        /// </summary>
        internal static string start_session {
            get {
                return ResourceManager.GetString("start_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submetido.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submeter questionário para avaliação.
        /// </summary>
        internal static string submit_a_form {
            get {
                return ResourceManager.GetString("submit_a_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submeta o questionário.
        /// </summary>
        internal static string submit_name {
            get {
                return ResourceManager.GetString("submit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submeta o questionário para avaliação.
        /// </summary>
        internal static string submit_name_entity {
            get {
                return ResourceManager.GetString("submit_name_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da submissão.
        /// </summary>
        internal static string submit_status {
            get {
                return ResourceManager.GetString("submit_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submeta o questionário.
        /// </summary>
        internal static string submit_value {
            get {
                return ResourceManager.GetString("submit_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submit_value_entity {
            get {
                return ResourceManager.GetString("submit_value_entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos de uso.
        /// </summary>
        internal static string terms_of_use {
            get {
                return ResourceManager.GetString("terms_of_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termos de uso.
        /// </summary>
        internal static string term_of_use {
            get {
                return ResourceManager.GetString("term_of_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem questionários &lt;strong&gt;reprovados&lt;/strong&gt;. Por favor, revise o questionário selecionando a cidade reprovada..
        /// </summary>
        internal static string there_are_not_approved_forms {
            get {
                return ResourceManager.GetString("there_are_not_approved_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passos para submeter um questionário..
        /// </summary>
        internal static string title_expimpform {
            get {
                return ResourceManager.GetString("title_expimpform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de perguntas respondidas.
        /// </summary>
        internal static string total_questions_answered {
            get {
                return ResourceManager.GetString("total_questions_answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuário.
        /// </summary>
        internal static string user_type {
            get {
                return ResourceManager.GetString("user_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar questionário.
        /// </summary>
        internal static string view_questions {
            get {
                return ResourceManager.GetString("view_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde....
        /// </summary>
        internal static string wait {
            get {
                return ResourceManager.GetString("wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi enviado um email com seu usuário e senha..
        /// </summary>
        internal static string we_sent_an_email_with_you_password_and_login {
            get {
                return ResourceManager.GetString("we_sent_an_email_with_you_password_and_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está prestes a responder o seguinte questionário:.
        /// </summary>
        internal static string you_are_answer_following_form {
            get {
                return ResourceManager.GetString("you_are_answer_following_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deve aceitar os termos e condições antes de realizar qualquer operação no site!.
        /// </summary>
        internal static string you_need_accept_terms {
            get {
                return ResourceManager.GetString("you_need_accept_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep.
        /// </summary>
        internal static string zipcode {
            get {
                return ResourceManager.GetString("zipcode", resourceCulture);
            }
        }
    }
}
